services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    networks:
      surikat-network:
      vpn-network:
        ipv4_address: 172.20.1.11
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - ./portainer_key.txt:/run/secrets/portainer:ro

volumes:
  portainer_data:
    name: portainer_data

networks:
  surikat-network:
    external: true
  vpn-network:
    external: true
    name: surikat-vpn

